services:

  db-host:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: dbpswd
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  server:
    build:
      context: .
      target: server
    init: true
    volumes:
      - ./src:/work
    depends_on:
      - db-host
    environment:
      POSTGRES_PASSWORD: dbpswd
    command:
      - python3.11
      - server.py
    healthcheck:
      test: "nc -z localhost 80"
      interval: 1s
      retries: 5

  test:
    build:
      context: .
      target: test
    init: true
    volumes:
      - ./tests:/work/tests
      - ./src/dba.py:/work/dba.py
    depends_on:
      server:
        condition: service_healthy
    environment:
      POSTGRES_PASSWORD: dbpswd
    command:
      - python3.11
      - -m
      - pytest
      - -sqx
      - tests
